name: Backend Checks

on: push

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  # This workflow contains a single job called "build"
  check-backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.*

      - name: Install dependencies
        working-directory: backend
        run: yarn install

      - name: Run tests
        working-directory: backend
        run:  yarn test

